### PR TITLE
SPM support

### PR DESCRIPTION
**Pull request by ikhsan**
Salam, 

This is my first stab to make the adhan library available for linux-based projects. These are the things I added:
- package definition
- docker support (I used it to run the tests on Linux)
- travis job to run on linux
- installation docs

I understand that docker and swift tests add crufts on the project (docker files, test manifest, etc). Let me know if you think this is too crowdy.

Jazakallah khair,

### CODE REVIEW

**Comment by z3bi** [comment]
Thank you for this contribution. I like the idea of adding SPM support, but I think it might be preferable to do it without adding docker or linux specific tests to the project. Also I don't think its necessary to add Package.swift to the Xcode project.

**Comment by ikhsan** [comment]
Sure, I can clean those up (the xcode proj, docker and the test). I did the docker because I want to make sure that all tests work in Linux.

**Comment by ikhsan** [comment]
Sure, I can clean those up (the xcode proj, docker and the test). I did the docker because I want to make sure that all tests work in Linux. And then I thought I'll just include it in the PR and ask.

**Comment by z3bi** [comment]
> Also what do you think about running the test in Linux as well with Travis?

I don't think that's necessary. Lets keep the travis tests just iOS for now.

**Pull request merged**
